PUT http://localhost:3001/api/user/inc/62879c5c57ae70c28fb31da1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkaXR5YSIsImVtYWlsIjoiYWRpdHlhQGdtaWFsLmNvbSIsInBob25lIjoiNjQ2NTQ1NjQiLCJpZCI6IjYyOGRkYWVlYjlmNWFiZWQ4YjYyZTcxYiIsImlhdCI6MTY1MzQ2Mzg4Mn0.jZpr5un4BSnTHDGH7TZ3XbJV5ApYWmmNZnDtaY33reY